name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGOLAB_URI: ${{ secrets.MONGOLAB_URI }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run seed
      - run: npm start &
      - run: npm test

  postman-tests:
    if: github.event_name == 'workflow_dispatch' # Trigger only manually
    runs-on: ubuntu-latest
    env:
      MONGOLAB_URI: ${{ secrets.MONGOLAB_URI }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman tests
        run: |
          newman run test/postman/postman_collection.json \
            --env-var BASE_URL=http://localhost:3030 \
            --env-var U_NAME=testuser123 \
            --env-var U_PASSWORD=secret